name: freeze cli
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test freeze
        run: |
         
          curl --location-trusted https://github.com/charmbracelet/freeze/releases/download/v0.1.6/freeze_0.1.6_amd64.deb -o a.deb
          sudo dpkg -i a.deb
          ls -l
          echo "000001"

          echo 333 | freeze -
          echo "000002"
          freeze --execute "pwd"
          echo "000003"
          freeze .github/workflows/freeze.yml -l yaml
          echo "000004"
          ls -l
          ./freeze dist/bita.structure.txt
          ls -l