name: Dot to svg
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install graphviz
        run: |
          sudo apt install -y graphviz
          cd graph
          if [[ ! -f svgs ]];then
              mkdir svgs
          fi
          for fname in `ls .`;do
              echo $fname
              noext=`basename $fname`
              outname="${noext}.svg"
              dot -Tsvg -o "./svgs/$outname" $fname
          done

      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: graph.svgs
          path: graph/svgs