name: Rust module dependencies
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo modules
        run: |
          cargo install cargo-modules
          cargo install flamegraph
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
      - uses: actions/checkout@v4
        with:
          repository: 'seanmonstar/reqwest'
      - name: flamegraph generator 
        if: ${{ contains('not work as expected', 'windows') }}
        run: |
          if [[ ! -d graph ]];then
            mkdir graph
          fi
          if [[ ! -d graph/svgs ]];then
              mkdir graph/svgs
          fi
          cd bitar
          cargo build -r --examples

          sudo `which flamegraph` -- ../target/release/examples/local-cloner > ../graph/svgs/compress.log
          sudo chmod 777 flamegraph.svg
          cp flamegraph.svg ../
          cd ..
          cp flamegraph.svg graph/svgs/local-cloner.svg
          sudo chmod 777 -R graph

          cd bitar
          sudo `which flamegraph` -- ../target/release/examples/in-place-cloner > ../graph/svgs/compress.log
          sudo chmod 777 flamegraph.svg
          cp flamegraph.svg ../
          cd ..
          cp flamegraph.svg graph/svgs/in-place-cloner.svg
          sudo chmod 777 -R graph
          
      - name: Graphical Module Structure
        run: |
          if [[ ! -d graph ]];then
            mkdir graph
          fi
          if [[ ! -d .bin ]];then
            mkdir .bin
          fi
          cd .bin 
          curl --location-trusted https://github.com/charmbracelet/freeze/releases/download/v0.1.6/freeze_0.1.6_amd64.deb -o freeze.deb
          sudo dpkg -i freeze.deb
          ls -l
          cd ..
          pwd
          if [[ ! -d graph/svgs ]];then
              mkdir graph/svgs
          fi
          cargo modules dependencies --package reqwest  --no-externs --no-sysroot > graph/reqwest.more.dep.dot
          cargo modules structure  --package reqwest  | freeze -l txt -o graph/svgs/reqwest.structure.svg -
          sudo apt-get install -y graphviz
          ls
          cd graph
          pwd
          if [[ ! -d svgs ]];then
              mkdir svgs
          fi
          for fname in `ls .`;do
              echo $fname
              if [[ -f $fname ]];then
                  if [[ $fname == *.dot ]];then
                    noext="${fname%.*}"
                    outname="${noext}.svg"
                    dot -Tsvg -o "./svgs/$outname" $fname
                    echo $outname
                  fi
              fi
          done
          
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: graph
          path: graph