name: Rust module dependencies
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo modules
        run: |
          cargo install cargo-modules
      - uses: actions/checkout@v4
        with:
          repository: 'oll3/bita'
      - name: Graphical Module Structure
        run: |
          if [[ ! -d graph ]];then
            mkdir graph
          fi
          cargo modules dependencies --package bitar --no-externs --no-fns --no-sysroot --no-traits --no-types --no-uses > graph/graph.dep.dot
          cargo modules dependencies --package bita > graph/bita.dep.dot
          sudo apt install -y graphviz
          cd graph
          if [[ ! -d svgs ]];then
              mkdir svgs
          fi
          for fname in `ls .`;do
              echo $fname
              if [[ -f $fname ]];then
                  noext="${fname%.*}"
                  outname="${noext}.svg"
                  dot -Tsvg -o "./svgs/$outname" $fname
                  echo $outname
              fi
          done
          cd ..
          cargo modules structure  --package bit > graph/bita.structure.txt
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: graph
          path: graph